### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pauldraper** [andyscott/rules_scala_annex#100]
Bazel core is Apache 2.0

**Comment by jjudd** [comment]
+1 for Apache 2.0.

Anything preventing us from setting Apache 2 as the license?

**Comment by pauldraper** [comment]
No.

**Comment by pauldraper** [comment]
I don't think so. @andyscott ?

**Comment by jjudd** [comment]
Friendly ping here. We good with Apache 2?

**Comment by andyscott** [comment]
Sounds good to me!

**Comment by jjudd** [comment]
I think because we don't have a CLA or an existing license, we'll need all contributors to agree to adding the license, yeah? Thankfully we only have 5 contributors so far.

I'm not lawyer, but everyone agreeing in this GitHub issue thread seems to create a decent paper trail.

@pauldraper @andyscott @jjudd @borkaehw @jvican do you agree to license this project (rules_scala_annex) under the Apache license 2.0?

**Comment by jjudd** [comment]
I agree to license this project (rules_scala_annex) and my contributions to it under the Apache license 2.0

**Comment by borkaehw** [comment]
I agree to license this project (rules_scala_annex) and my contributions to it under the Apache license 2.0

**Comment by pauldraper** [comment]
I agree to license this project (rules_scala_annex) and my contributions to it under the Apache license 2.0

**Comment by andyscott** [comment]
I agree to license this project (rules_scala_annex) and my contributions to it under the Apache license 2.0
