### ISSUE TITLE
I can't get scalafmt to work through rules_scala_annex

### ISSUE THREAD

**Issue by onzo-dave-hinton** [andyscott/rules_scala_annex#120]
I attempted to follow the instructions in the README for running scalafmt.

On my first attempt I got these errors:

    ERROR: /Users/dave.hinton/vc/bazel-scalafmt-playground/WORKSPACE:29:1: file '@rules_scala_annex//rules/scalafmt:workspace.bzl' does not contain symbol 'scalafmt_default'
    ERROR: /Users/dave.hinton/vc/bazel-scalafmt-playground/WORKSPACE:30:1: name 'scalafmt_default' is not defined
    ERROR: Error evaluating WORKSPACE file

After brief investigation, I guessed that I should use `scalafmt_default_config` instead of `scalafmt_default`. This seemed to be an improvement, but still gave me an error:

    ERROR: Analysis of target '//:format' failed; build aborted: no such package '@scalafmt_com_geirsson_metaconfig_core_2_12//': The repository could not be resolved

I understand that rules_scala_annex is experimental and that perhaps scalafmt support is broken at the moment. On the other hand, if the problem is just that the documentation is wrong or misleading, I am happy to open a PR just as soon as someone has explained to me how to get it working :-)

Minimal workspace I was using for this test: https://gist.github.com/onzo-dave-hinton/b0b745095036077ef3ef053f3102d978 (includes commit history).

    $ bazel version
    Build label: 0.17.2-homebrew
    Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Fri Sep 28 10:42:37 2018 (1538131357)
    Build timestamp: 1538131357
    Build timestamp as int: 1538131357

**Comment by jjudd** [comment]
Hi. Sorry that you ran into some trouble with this. Scalafmt is working internally for us at Lucid, so we'll take a look at see if we can figure out what is going on here.

**Comment by JaredNeil** [comment]
First of all, thanks for the great report. The gist was very useful in identifying the problem.
Looks like along with `scalafmt_default_config` you also need to load and call `scalafmt_repositories` ([gist](https://gist.github.com/JaredNeil/c207bac9ce498b08094403db349aeb62/revisions)).
I've opened a PR to update the README: https://github.com/andyscott/rules_scala_annex/pull/121

**Comment by jjudd** [comment]
The README has been updated -  #121 has been merged. @onzo-dave-hinton please let me know if that does not fix your issue and I'll reopen.

**Comment by onzo-dave-hinton** [comment]
@jjudd Just to confirm, that fixes my issue — it now runs without errors :-)

One other note: it was surprising to me that my source file was not reformatted in place. In retrospect, given what little I know of Bazel's execution model, this makes sense, but it is different from what I am used to with SBT. Would it be worth adding a note to the README explaining where to find the reformatted source files?

**Comment by JaredNeil** [comment]
Ah yes. Bazel does not let you update "source" files as part of a build. So we work around this using the test runner script. If you pass the path of the workspace root as the first parameter to the test runner script it will copy the files instead of doing a diff.

`bazel run :format-format .` or `bazel-bin/format-format .` should work.

This is definitely something that should be added to the README.

**Comment by onzo-dave-hinton** [comment]
The test runner script isn't working for me :-(

I've pushed another commit to the gist, and full details in the commit message, but briefly:

- `bazel run :format-format .` runs without error, but does not reformat my source files in place
- the `manifest.txt` file that the script reads from lacks expected path information: in `Hello.scala Hello.scala`, the second filename should refer to the formatted file (although given my lack of understanding, it's possible instead that the manifest is correct and the script is buggy)

I don't know how `manifest.txt` is generated, so can't investigate further without help.

(Should I open a separate issue for this?)

**Comment by pauldraper** [comment]
@onzo-dave-hinton yes go ahead and open another issue if it still does not work.

But,

1. I believe Jared is mistaken and `bazel run :format-format .` does not work, because the first argument needs to be the workspace root, and `bazel run` runs in the execroot. This is why the README had `bazel run :format "$(bazel info | grep workspace: | cut -d' ' -f2)"` (However, directly running `bazel-bin/format-format .` runs in the current directory and works.)
2. #124 simplified all this so that with the latest version you only have to do `bazel run :format-format` to format in-place (no need to pass workspace root as the first argument).
